# -*- coding: utf-8 -*-
"""Cluster_revisi_1.1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uao6v4N0h7k5Yn2wJYIW_obeqDmmMW6q
"""

# =========================
# 1. IMPORT LIBRARY
# =========================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import folium

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score
from sklearn.metrics import davies_bouldin_score

# =========================
# 2. LOAD DATA
# =========================
df = pd.read_excel('Hasil_Clustering_UMKM_dengan_jenis.xlsx')

# =========================
# 3. DATA CLEANING
# =========================

# Hapus data kosong
df = df.dropna()

# Hapus data duplikat
df = df.drop_duplicates()

# Pastikan koordinat numerik
df['latitude'] = pd.to_numeric(df['latitude'], errors='coerce')
df['longitude'] = pd.to_numeric(df['longitude'], errors='coerce')

# Hapus NaN setelah konversi
df = df.dropna()

# Filter wilayah Pekanbaru (opsional)
df = df[
    (df['latitude'] >= 0.40) & (df['latitude'] <= 0.60) &
    (df['longitude'] >= 101.20) & (df['longitude'] <= 101.50)
]

df = df.reset_index(drop=True)

print("Jumlah data setelah cleaning :", len(df))

# 4. DATA SELECTION
# =========================

# Ambil atribut untuk clustering
X = df[['latitude', 'longitude','kampus','pasar','perumahan','jalanUtama']]

# =========================
# 5. DATA TRANSFORMATION
# =========================

# Normalisasi data
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

import pandas as pd
import numpy as np
from sklearn.cluster import KMeans

# Menyimpan hasil iterasi
hasil_iterasi = []

# Pengujian iterasi K-Means
for i in range(1, 11):

    kmeans = KMeans(
        n_clusters=3,
        max_iter=i,
        random_state=42,
        n_init=1
    )

    kmeans.fit(X_scaled)

    hasil_iterasi.append({
        'Iterasi': i,
        'Inertia': kmeans.inertia_,
        'Jumlah Cluster': 3
    })

# Membuat DataFrame
df_iterasi = pd.DataFrame(hasil_iterasi)

# Menampilkan tabel
print(df_iterasi)

# Simpan ke Excel
nama_file = "hasil_pengujian_iterasi_kmeans.xlsx"
df_iterasi.to_excel(nama_file, index=False)

print(f"File tersimpan: {nama_file}")

# Download di Google Colab
from google.colab import files
files.download(nama_file)

# =========================
# ELBOW METHOD
# =========================

inertia = []
K_range = range(1, 7)

for k in K_range:

    kmeans = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )

    kmeans.fit(X_scaled)

    # Simpan nilai inertia/SSE
    inertia.append(kmeans.inertia_)

# =========================
# VISUALISASI ELBOW METHOD
# =========================

plt.figure(figsize=(8,5))

plt.plot(
    K_range,
    inertia,
    marker='o'
)

plt.title('Elbow Method')
plt.xlabel('Jumlah Cluster (K)')
plt.ylabel('Inertia / SSE')

plt.grid(True)
plt.show()

# =========================
# 6. PENGUJIAN EVALUASI K
# =========================

k_range = range(2, 7)

silhouette_scores = []
dbi_scores = []

print("\nHASIL EVALUASI CLUSTER\n")

for k in k_range:

    kmeans = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )

    labels = kmeans.fit_predict(X_scaled)

    sil_score = silhouette_score(X_scaled, labels)
    dbi_score = davies_bouldin_score(X_scaled, labels)

    silhouette_scores.append(sil_score)
    dbi_scores.append(dbi_score)

    print(f"K = {k}")
    print(f"Silhouette Score : {sil_score:.4f}")
    print(f"Davies-Bouldin Index : {dbi_score:.4f}")
    print("-" * 40)

# =========================
# 7. VISUALISASI EVALUASI
# =========================

# Grafik Silhouette Score
plt.figure(figsize=(8,5))
plt.plot(k_range, silhouette_scores, marker='o')
plt.title('Silhouette Score')
plt.xlabel('Jumlah Cluster (K)')
plt.ylabel('Score')
plt.grid(True)
plt.show()

# Grafik DBI
plt.figure(figsize=(8,5))
plt.plot(k_range, dbi_scores, marker='o')
plt.title('Davies-Bouldin Index')
plt.xlabel('Jumlah Cluster (K)')
plt.ylabel('DBI')
plt.grid(True)
plt.show()

# =========================
# 8. MENETAPKAN BEST K = 3
# =========================

best_k = 3

print("\n===================================")
print(f"BEST K YANG DIGUNAKAN = {best_k}")
print("===================================")

# Menampilkan evaluasi K=3
index_k3 = list(k_range).index(3)

print(f"Silhouette Score K=3 : {silhouette_scores[index_k3]:.4f}")
print(f"DBI K=3 : {dbi_scores[index_k3]:.4f}")

# =========================
# 9. PROSES K-MEANS FINAL
# =========================

kmeans_final = KMeans(
    n_clusters=best_k,
    random_state=42,
    n_init=10
)

df['cluster'] = kmeans_final.fit_predict(X_scaled)

# =========================
# 10. JUMLAH DATA TIAP CLUSTER
# =========================

print("\nJumlah Data Tiap Cluster:")
print(df['cluster'].value_counts())

# =========================
# 11. HITUNG CENTROID
# =========================

centroid = df.groupby('cluster')[['latitude', 'longitude']].mean()

print("\nCentroid Cluster:")
print(centroid)

# =========================
# 12. VISUALISASI CLUSTER MATPLOTLIB
# =========================

plt.figure(figsize=(8,6))

colors = ['blue', 'red', 'green']

for cluster in sorted(df['cluster'].unique()):

    cluster_data = df[df['cluster'] == cluster]

    plt.scatter(
        cluster_data['longitude'],
        cluster_data['latitude'],
        label=f'Cluster {cluster}',
        color=colors[cluster]
    )

# Plot centroid
plt.scatter(
    centroid['longitude'],
    centroid['latitude'],
    color='black',
    marker='X',
    s=200,
    label='Centroid'
)

plt.title('Visualisasi Cluster UMKM')
plt.xlabel('Longitude')
plt.ylabel('Latitude')
plt.legend()
plt.grid(True)
plt.show()

# =========================
# UJI ITERASI K-MEANS
# =========================

print("Jumlah Iterasi K-Means :", kmeans_final.n_iter_)

# =========================
# 13. VISUALISASI FOLIUM MAP
# =========================

# Titik tengah peta
center_lat = df['latitude'].mean()
center_lon = df['longitude'].mean()

m = folium.Map(
    location=[center_lat, center_lon],
    zoom_start=12
)

# Warna cluster
cluster_colors = {
    0: 'blue',
    1: 'green',
    2: 'red'
}

# Menampilkan titik UMKM
for _, row in df.iterrows():

    folium.CircleMarker(
        location=[row['latitude'], row['longitude']],
        radius=5,
        color=cluster_colors[row['cluster']],
        fill=True,
        fill_color=cluster_colors[row['cluster']],
        fill_opacity=0.7,

        popup=f"""
        Cluster : {row['cluster']}
        <br>
        Latitude : {row['latitude']}
        <br>
        Longitude : {row['longitude']}
        """
    ).add_to(m)

# Menampilkan centroid
for cluster, row in centroid.iterrows():

    folium.Marker(
        location=[row['latitude'], row['longitude']],
        popup=f"Centroid Cluster {cluster}",

        icon=folium.Icon(
            color='black',
            icon='info-sign'
        )

    ).add_to(m)

# =========================
# 14. LEGENDA PETA
# =========================

legend_html = '''
<div style="
position: fixed;
bottom: 50px;
left: 50px;
width: 180px;
background-color: white;
border:2px solid grey;
z-index:9999;
font-size:14px;
padding: 10px;
">

<b>Legenda Cluster</b><br>

<span style="color:green;">●</span> Cluster 0<br>
<span style="color:blue;">●</span> Cluster 1<br>
<span style="color:red;">●</span> Cluster 2<br>

</div>
'''

m.get_root().html.add_child(folium.Element(legend_html))

# =========================
# 15. TAMPILKAN PETA
# =========================

m

output_file = "hasil_clustering_umkm.xlsx"

df.to_excel(output_file, index=False)

print(f"File berhasil disimpan: {output_file}")

# ===================================
# DOWNLOAD FILE
# ===================================

from google.colab import files

files.download(output_file)